version: '3.3'

services:
  db:
    image: postgres:12.3
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres

  app:
    # Keep this in lock-step with docker/Dockerfile.production
    image: thechangelog/runtime:2019-11-27T16.20.17Z
    working_dir: /app
    command: >
      /bin/sh -c 'apt-get update && apt-get install -y inotify-tools &&
      mix local.hex --force &&
      mix local.rebar --force &&
      mix deps.get &&
      (cd assets && yarn install) &&
      mix ecto.setup &&
      mix phx.gen.cert &&
      mix phx.server'
    environment:
      DB_HOST: db
      DB_NAME: changelog_dev
      DB_USER: postgres
      DB_PASS: postgres
      VIRTUAL_HOST: &host "${HOST:-localhost}"
      HOST: *host
    # https://docs.docker.com/compose/compose-file/#ports
    ports:
      - '4000:4000'
      - '4001:4001'
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  db-data: {}
