#@data/values
#! https://github.com/k14s/ytt/blob/master/examples/data-values/values.yml
#! If necessary, these values can be overwritten in a number of ways: https://github.com/k14s/ytt/blob/master/docs/ytt-data-values.md
---
#! provided just-in-time
namespace:
fqdn:
grafana_cloud:
  url:
github:
  allowed_organizations:
  client_id:
  client_secret:
  team_ids:
changelog:
  app:
    name:
    namespace:
