
honeycomb:
  # Specify your Honeycomb API KEY to send events
  apiKey: YOUR_API_KEY
  # Specify host URL to send all events to
  apiHost: https://api.honeycomb.io/
  # Specify the name of an existing secret resource containing your Honeycomb API KEY instead of having a secret resource created
  existingSecret: ""

watchers:
  # - dataset: kubernetes-logs
  #   labelSelector: "component=kube-apiserver,tier=control-plane"
  #   namespace: kube-system
  #   parser: glog
  # - dataset: kubernetes-logs
  #   labelSelector: "component=kube-scheduler,tier=control-plane"
  #   namespace: kube-system
  #   parser: glog
  # - dataset: kubernetes-logs
  #   labelSelector: "component=kube-controller-manager,tier=control-plane"
  #   namespace: kube-system
  #   parser: glog
  # - dataset: kubernetes-logs
  #   labelSelector: "k8s-app=kube-proxy"
  #   namespace: kube-system
  #   parser: glog
  # - dataset: kubernetes-logs
  #   labelSelector: "k8s-app=kube-dns"
  #   namespace: kube-system
  #   parser: glog
  - dataset: ingress-nginx
    labelSelector: app.kubernetes.io/name=ingress-nginx
    namespace: ingress-nginx
    parser: json

# Disable metrics to make room for Fastly events
metrics:
  enabled: false
  dataset: kubernetes-metrics
  clusterName: k8s-cluster
  metricGroups:
    - node
    - pod
    - volume
  # omitLabels:
  #   - "private_label"
  # additionalFields:
  #   region: us-east-1

# agent log verbosity: warn, info, debug, trace
verbosity: info

# splitLogging directs trace, debug, info, and warn log levels to stdout rather than stderr
splitLogging: false

# additionalFields:
#   cluster_name: dev_cluster

nameOverride: ""
fullnameOverride: ""
imagePullSecrets: []


image:
  repository: honeycombio/honeycomb-kubernetes-agent
  # Overrides the image tag whose default is the chart version.
  tag: ""
  pullPolicy: IfNotPresent

terminationGracePeriodSeconds: 30

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000


securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

# Tolerate agent to run on all nodes by default
tolerations:
  - effect: NoSchedule
    key: node.alpha.kubernetes.io/role
    operator: Exists
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
    operator: Exists

affinity: {}

## Optional priorityClassName for Honeycomb Agent
priorityClassName: ""

rbac:
  # Specifies whether roles based access control rules should be created.
  create: true


serviceAccount:
  # Specifies whether a service account should be created.
  create: true
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
  # Annotations to add to the service account
  annotations: {}
