name: mix test
on:
  push: {branches: master}
  pull_request: {branches: master}
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12.3
        env:
          POSTGRES_USER: postgres
          POSTGRES_DB: changelog_test
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    container:
      image: thechangelog/runtime:2021-05-28T08.47.44Z
      env:
        MIX_ENV: test
        DB_NAME: changelog_test
        DB_HOST: postgres
        DB_USER: postgres
        DB_PASS: postgres
    steps:
      - uses: actions/checkout@v2
      - run: mix do local.rebar --force, local.hex --force
      - run: mix deps.get
      - run: mix deps.compile
      - run: cd assets && yarn install --frozen-lockfile
      - run: mix test
      - run: mix format --check-formatted
        continue-on-error: true
